versions:
 - v0
 - v1
 - v2

hosts:
 - host: "*"
   vroot: default

 - host: "*.zunzun.io"
   vroot: default

 - host: ejemplo.org
   vroot: ejemplo

 - host: api.ejemplo.org
   vroot: ejemplo

routes:
 default:
   - url: /test/.*
     handler: test
     methods:
      - GET
      - POST
      - PUT

   - url: /(md5|sha1|sha256|sha512)(/.*)?
     handler: hash
     methods:
      - GET

   - url: /.*
     handler: default

 ejemplo:
   - url: /.*
     handler: default
     methods:
      - ALL
